package:
  name: dolo
  version: "0.4.9.7"

source:
  fn: dolo-0.4.9.7.tar.gz
  path: ../dolo/
  url: https://github.com/EconForge/dolo/archive/v0.4.9.7.tar.gz
  md5: 47b515a89685b46da369eafc21c3901e

build:
  noarch_python: True

requirements:
  build:
    - python
    - pyyaml
    - numba
    - numpy
    - sympy
    - pandas
    - xarray
    - ipython
    - interpolation
    - ruamel.yaml
    - quantecon
    - dolang

  run:
    - python
    - pyyaml
    - numba
    - numpy
    - sympy
    - pandas
    - xarray
    - ipython
    - interpolation
    - ruamel.yaml
    - quantecon
    - dolang

  test:
    imports:
      - dolo

about:
  home: http://albop.github.com/dolo/
  license: BSD-2
  summary: 'Economic modelling in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
